In [2]:
pip install xmltodict

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: xmltodict in /usr/local/lib/python3.7/dist-packages (0.13.0)

In [3]:
!curl https://ecommwebsitedata.s3.amazonaws.com/acm-sf-chapter-hackathon-big.zip --output bestbuy.zip

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 92  893M   92  827M    0     0  29.8M      0  0:00:29  0:00:27  0:00:02 31.9M
100  893M  100  893M    0     0  30.0M      0  0:00:29  0:00:29 --:--:-- 32.7M

In [4]:
!ls

bestbuy.zip  popular_skus.csv  product_data	 product_data.tar.gz  test.csv
drive	     popular_skus.py   product_data.tar  sample_data	      train.csv

In [5]:
!unzip bestbuy.zip

Archive:  bestbuy.zip
replace popular_skus.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace popular_skus.py? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace product_data.tar.gz? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace test.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace train.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n

In [6]:
from google.colab import drive

In [7]:
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [8]:
!mkdir /content/drive/MyDrive/bestbuy

mkdir: cannot create directory ‘/content/drive/MyDrive/bestbuy’: File exists

In [9]:
!cp train.csv /content/drive/MyDrive/bestbuy

In [10]:
!cp test.csv /content/drive/MyDrive/bestbuy

In [11]:
!cp popular_skus.csv /content/drive/MyDrive/bestbuy

In [12]:
!gunzip product_data.tar.gz

gzip: product_data.tar already exists; do you wish to overwrite (y or n)? n
	not overwritten

In [13]:
!tar xvf product_data.tar

product_data/
product_data/categories/
product_data/categories/categories_0001_abcat0010000_to_pcmcat99300050000.xml
product_data/reviews/
product_data/reviews/reviews_0010_1906234_to_2063675.xml
product_data/reviews/reviews_0012_2151940_to_2284992.xml
product_data/reviews/reviews_0037_6889364_to_6950068.xml
product_data/reviews/reviews_0004_501835_to_691133.xml
product_data/reviews/reviews_0018_4017769_to_4160192.xml
product_data/reviews/reviews_0007_1117796_to_1382936.xml
product_data/reviews/reviews_0016_3197161_to_3395314.xml
product_data/reviews/reviews_0027_5806868_to_6022633.xml
product_data/reviews/reviews_0014_2440655_to_2799035.xml
product_data/reviews/reviews_0015_2799189_to_3197154.xml
product_data/reviews/reviews_0021_4286995_to_4472320.xml
product_data/reviews/reviews_0024_5130266_to_5247642.xml
product_data/reviews/reviews_0035_6701490_to_6801194.xml
product_data/reviews/reviews_0005_691144_to_831905.xml
product_data/reviews/reviews_0022_4472324_to_4833387.xml
product_data/reviews/reviews_0023_4833425_to_5130263.xml
product_data/reviews/reviews_0011_2063679_to_2151936.xml
product_data/reviews/reviews_0017_3395388_to_4017768.xml
product_data/reviews/reviews_0003_345248_to_501823.xml
product_data/reviews/reviews_0025_5247643_to_5363104.xml
product_data/reviews/reviews_0006_831928_to_1117787.xml
product_data/reviews/reviews_0020_4209473_to_4286992.xml
product_data/reviews/reviews_0045_7736346_to_7762248.xml
product_data/reviews/reviews_0043_7479787_to_7610126.xml
product_data/reviews/reviews_0036_6801200_to_6889357.xml
product_data/reviews/reviews_0041_7269649_to_7387421.xml
product_data/reviews/reviews_0019_4160194_to_4209454.xml
product_data/reviews/reviews_0030_6358125_to_6396149.xml
product_data/reviews/reviews_0040_7198571_to_7269645.xml
product_data/reviews/reviews_0026_5363109_to_5806838.xml
product_data/reviews/reviews_0044_7610127_to_7736345.xml
product_data/reviews/reviews_0028_6022641_to_6172272.xml
product_data/reviews/reviews_0033_6486865_to_6587831.xml
product_data/reviews/reviews_0001_24122_to_98772.xml
product_data/reviews/reviews_0013_2285000_to_2440628.xml
product_data/reviews/reviews_0039_7039382_to_7198559.xml
product_data/reviews/reviews_0002_98780_to_345240.xml
product_data/reviews/reviews_0034_6587839_to_6701463.xml
product_data/reviews/reviews_0032_6423025_to_6486864.xml
product_data/reviews/reviews_0042_7387427_to_7479780.xml
product_data/reviews/reviews_0038_6950072_to_7039369.xml
product_data/reviews/reviews_0031_6396154_to_6423017.xml
product_data/reviews/reviews_0009_1597878_to_1906168.xml
product_data/reviews/reviews_0029_6172275_to_6358111.xml
product_data/reviews/reviews_0008_1382981_to_1597862.xml
product_data/products/
product_data/products/products_0135_12585295_to_12641439.xml
product_data/products/products_0154_13954278_to_14012757.xml
product_data/products/products_0085_8771938_to_8856419.xml
product_data/products/products_0018_2035443_to_2098517.xml
product_data/products/products_0045_4230576_to_4326232.xml
product_data/products/products_0049_4725587_to_4810643.xml
product_data/products/products_0117_11594447_to_11666315.xml
product_data/products/products_0127_12146297_to_12201565.xml
product_data/products/products_0130_12309664_to_12363186.xml
product_data/products/products_0246_20069161_to_20128686.xml
product_data/products/products_0236_19379882_to_19452187.xml
product_data/products/products_0235_19312288_to_19379873.xml
product_data/products/products_0108_10888907_to_10972432.xml
product_data/products/products_0183_15706595_to_15778623.xml
product_data/products/products_0056_5412252_to_5573998.xml
product_data/products/products_0230_18957618_to_19040862.xml
product_data/products/products_0115_11436494_to_11514097.xml
product_data/products/products_0197_16592224_to_16661284.xml
product_data/products/products_0026_2685115_to_2762861.xml
product_data/products/products_0217_17990532_to_18069368.xml
product_data/products/products_0065_6685928_to_6785115.xml
product_data/products/products_0255_9999141300050003_to_9999184200050032.xml
product_data/products/products_0068_6976034_to_7062867.xml
product_data/products/products_0182_15635699_to_15706586.xml
product_data/products/products_0020_2180446_to_2282074.xml
product_data/products/products_0120_11768321_to_11821246.xml
product_data/products/products_0159_14273724_to_14333777.xml
product_data/products/products_0106_10740362_to_10811357.xml
product_data/products/products_0176_15282784_to_15339108.xml
product_data/products/products_0016_1841154_to_1937676.xml
product_data/products/products_0046_4326241_to_4516198.xml
product_data/products/products_0219_18138409_to_18197069.xml
product_data/products/products_0143_13084146_to_13158058.xml
product_data/products/products_0249_20259278_to_20333085.xml
product_data/products/products_0054_5196931_to_5288949.xml
product_data/products/products_0252_20459355_to_999928600050002.xml
product_data/products/products_0042_3952217_to_4040683.xml
product_data/products/products_0187_15963147_to_16028923.xml
product_data/products/products_0223_18434995_to_18509097.xml
product_data/products/products_0224_18509103_to_18587072.xml
product_data/products/products_0166_14689973_to_14754722.xml
product_data/products/products_0146_13328785_to_13417778.xml
product_data/products/products_0227_18733993_to_18807545.xml
product_data/products/products_0237_19452196_to_19524448.xml
product_data/products/products_0096_9825321_to_9942574.xml
product_data/products/products_0061_6089573_to_6167961.xml
product_data/products/products_0214_17777005_to_17842836.xml
product_data/products/products_0254_999994800050007_to_9999141300050002.xml
product_data/products/products_0041_3868528_to_3952208.xml
product_data/products/products_0104_10590826_to_10667851.xml
product_data/products/products_0059_5929953_to_6014733.xml
product_data/products/products_0062_6167989_to_6299917.xml
product_data/products/products_0066_6785124_to_6877613.xml
product_data/products/products_0089_9123281_to_9216485.xml
product_data/products/products_0075_7767767_to_7873009.xml
product_data/products/products_0102_10436842_to_10511243.xml
product_data/products/products_0180_15514668_to_15571659.xml
product_data/products/products_0216_17913402_to_17990523.xml
product_data/products/products_0114_11358997_to_11436485.xml
product_data/products/products_0023_2459798_to_2537366.xml
product_data/products/products_0092_9393373_to_9489038.xml
product_data/products/products_0144_13158067_to_13245954.xml
product_data/products/products_0034_3328759_to_3408351.xml
product_data/products/products_0174_15166918_to_15226006.xml
product_data/products/products_0071_7281318_to_7425574.xml
product_data/products/products_0232_19108675_to_19176217.xml
product_data/products/products_0213_17695905_to_17776998.xml
product_data/products/products_0131_12363195_to_12418261.xml
product_data/products/products_0091_9305682_to_9393364.xml
product_data/products/products_0124_11982535_to_12038831.xml
product_data/products/products_0083_8588432_to_8680233.xml
product_data/products/products_0072_7425583_to_7565182.xml
product_data/products/products_0251_20397415_to_20459346.xml
product_data/products/products_0052_4959708_to_5051409.xml
product_data/products/products_0043_4040692_to_4133508.xml
product_data/products/products_0178_15398366_to_15457578.xml
product_data/products/products_0128_12201574_to_12256248.xml
product_data/products/products_0051_4879787_to_4959691.xml
product_data/products/products_0194_16422248_to_16477787.xml
product_data/products/products_0101_10359694_to_10436833.xml
product_data/products/products_0029_2914154_to_3002761.xml
product_data/products/products_0094_9572839_to_9709324.xml
product_data/products/products_0079_8225397_to_8315931.xml
product_data/products/products_0107_10811366_to_10888881.xml
product_data/products/products_0157_14134901_to_14201829.xml
product_data/products/products_0064_6448276_to_6685919.xml
product_data/products/products_0084_8680242_to_8771929.xml
product_data/products/products_0047_4516223_to_4625542.xml
product_data/products/products_0228_18807554_to_18879796.xml
product_data/products/products_0145_13245963_to_13328776.xml
product_data/products/products_0204_17065293_to_17144323.xml
product_data/products/products_0036_3476045_to_3543767.xml
product_data/products/products_0190_16164311_to_16238108.xml
product_data/products/products_0167_14754731_to_14825692.xml
product_data/products/products_0055_5288951_to_5412243.xml
product_data/products/products_0248_20193324_to_20259269.xml
product_data/products/products_0097_9942583_to_10127329.xml
product_data/products/products_0155_14012766_to_14073245.xml
product_data/products/products_0011_1304779_to_1387582.xml
product_data/products/products_0168_14825709_to_14881826.xml
product_data/products/products_0181_15571668_to_15635671.xml
product_data/products/products_0053_5051427_to_5196922.xml
product_data/products/products_0033_3239757_to_3328731.xml
product_data/products/products_0192_16295821_to_16351387.xml
product_data/products/products_0129_12256275_to_12309655.xml
product_data/products/products_0027_2762943_to_2840956.xml
product_data/products/products_0242_19788476_to_19863856.xml
product_data/products/products_0121_11821255_to_11872048.xml
product_data/products/products_0069_7062876_to_7193262.xml
product_data/products/products_0019_2098526_to_2180438.xml
product_data/products/products_0136_12641448_to_12694701.xml
product_data/products/products_0035_3408360_to_3476039.xml
product_data/products/products_0087_8944798_to_9037801.xml
product_data/products/products_0014_1572108_to_1742733.xml
product_data/products/products_0074_7675401_to_7767749.xml
product_data/products/products_0038_3618062_to_3691856.xml
product_data/products/products_0234_19241696_to_19312279.xml
product_data/products/products_0058_5749951_to_5929944.xml
product_data/products/products_0067_6877702_to_6976025.xml
product_data/products/products_0050_4810661_to_4879784.xml
product_data/products/products_0202_16928194_to_16996609.xml
product_data/products/products_0105_10667904_to_10740353.xml
product_data/products/products_0164_14567104_to_14626639.xml
product_data/products/products_0212_17616037_to_17695898.xml
product_data/products/products_0147_13417787_to_13491018.xml
product_data/products/products_0132_12418271_to_12472121.xml
product_data/products/products_0032_3150850_to_3239748.xml
product_data/products/products_0253_999928700050000_to_999994800050006.xml
product_data/products/products_0162_14450603_to_14508213.xml
product_data/products/products_0243_19863865_to_19939021.xml
product_data/products/products_0113_11280712_to_11358988.xml
product_data/products/products_0012_1387591_to_1471909.xml
product_data/products/products_0218_18069377_to_18138392.xml
product_data/products/products_0025_2610464_to_2685106.xml
product_data/products/products_0199_16725484_to_16792222.xml
product_data/products/products_0173_15110256_to_15166909.xml
product_data/products/products_0171_14997042_to_15053763.xml
product_data/products/products_0009_1156156_to_1230126.xml
product_data/products/products_0028_2840965_to_2914145.xml
product_data/products/products_0239_19595739_to_19657975.xml
product_data/products/products_0203_16996618_to_17065284.xml
product_data/products/products_0010_1230144_to_1304774.xml
product_data/products/products_0169_14881835_to_14939034.xml
product_data/products/products_0179_15457587_to_15514659.xml
product_data/products/products_0247_20128695_to_20193315.xml
product_data/products/products_0003_518229_to_606384.xml
product_data/products/products_0133_12472139_to_12528669.xml
product_data/products/products_0188_16028932_to_16101086.xml
product_data/products/products_0112_11203235_to_11280696.xml
product_data/products/products_0076_7873018_to_7969638.xml
product_data/products/products_0088_9037829_to_9123272.xml
product_data/products/products_0063_6299926_to_6448267.xml
product_data/products/products_0215_17842845_to_17913395.xml
product_data/products/products_0015_1742742_to_1841136.xml
product_data/products/products_0195_16477796_to_16533333.xml
product_data/products/products_0040_3781991_to_3868519.xml
product_data/products/products_0070_7193271_to_7281309.xml
product_data/products/products_0238_19524457_to_19595711.xml
product_data/products/products_0170_14939043_to_14997033.xml
product_data/products/products_0158_14201838_to_14273715.xml
product_data/products/products_0110_11054235_to_11127345.xml
product_data/products/products_0007_1002897_to_1067124.xml
product_data/products/products_0021_2282078_to_2380024.xml
product_data/products/products_0122_11872057_to_11922459.xml
product_data/products/products_0109_10972441_to_11054226.xml
product_data/products/products_0209_17399325_to_17465752.xml
product_data/products/products_0139_12810595_to_12867953.xml
product_data/products/products_0048_4625551_to_4725585.xml
product_data/products/products_0207_17270579_to_17335288.xml
product_data/products/products_0201_16862502_to_16928185.xml
product_data/products/products_0210_17465761_to_17538942.xml
product_data/products/products_0256_9999184200050033_to_9999186400050044.xml
product_data/products/products_0082_8498486_to_8588414.xml
product_data/products/products_0142_13024309_to_13084137.xml
product_data/products/products_0172_15053772_to_15110247.xml
product_data/products/products_0125_12038841_to_12092381.xml
product_data/products/products_0208_17335297_to_17399316.xml
product_data/products/products_0005_722800_to_846222.xml
product_data/products/products_0086_8856428_to_8944789.xml
product_data/products/products_0008_1067160_to_1156147.xml
product_data/products/products_0078_8107452_to_8225388.xml
product_data/products/products_0001_2570_to_430420.xml
product_data/products/products_0099_10203969_to_10281018.xml
product_data/products/products_0090_9216494_to_9305673.xml
product_data/products/products_0103_10511252_to_10590817.xml
product_data/products/products_0093_9489047_to_9572811.xml
product_data/products/products_0231_19040871_to_19108666.xml
product_data/products/products_0152_13821206_to_13890186.xml
product_data/products/products_0189_16101095_to_16164302.xml
product_data/products/products_0141_12951273_to_13024292.xml
product_data/products/products_0220_18197078_to_18274272.xml
product_data/products/products_0013_1471918_to_1572104.xml
product_data/products/products_0057_5574014_to_5749942.xml
product_data/products/products_0116_11514104_to_11594438.xml
product_data/products/products_0160_14333786_to_14393578.xml
product_data/products/products_0193_16351396_to_16422239.xml
product_data/products/products_0150_13646904_to_13735238.xml
product_data/products/products_0002_430439_to_518210.xml
product_data/products/products_0126_12092399_to_12146288.xml
product_data/products/products_0233_19176226_to_19241687.xml
product_data/products/products_0123_11922468_to_11982526.xml
product_data/products/products_0250_20333094_to_20397406.xml
product_data/products/products_0222_18353936_to_18434986.xml
product_data/products/products_0077_7969647_to_8107443.xml
product_data/products/products_0060_6014751_to_6089564.xml
product_data/products/products_0134_12528678_to_12585286.xml
product_data/products/products_0196_16533342_to_16592215.xml
product_data/products/products_0006_846231_to_1002890.xml
product_data/products/products_0244_19939049_to_20004526.xml
product_data/products/products_0037_3543776_to_3618053.xml
product_data/products/products_0245_20004535_to_20069152.xml
product_data/products/products_0229_18879805_to_18957609.xml
product_data/products/products_0226_18658629_to_18733984.xml
product_data/products/products_0022_2380033_to_2459734.xml
product_data/products/products_0039_3691865_to_3781982.xml
product_data/products/products_0100_10281045_to_10359676.xml
product_data/products/products_0149_13563477_to_13646897.xml
product_data/products/products_0177_15339117_to_15398357.xml
product_data/products/products_0191_16238796_to_16295812.xml
product_data/products/products_0080_8315959_to_8400517.xml
product_data/products/products_0163_14508222_to_14567097.xml
product_data/products/products_0151_13735247_to_13821199.xml
product_data/products/products_0211_17538951_to_17616028.xml
product_data/products/products_0184_15778632_to_15842484.xml
product_data/products/products_0118_11666324_to_11716645.xml
product_data/products/products_0161_14393587_to_14450596.xml
product_data/products/products_0073_7565379_to_7675367.xml
product_data/products/products_0017_1937685_to_2035434.xml
product_data/products/products_0185_15842493_to_15902472.xml
product_data/products/products_0148_13491027_to_13563468.xml
product_data/products/products_0095_9709333_to_9825279.xml
product_data/products/products_0205_17144332_to_17207023.xml
product_data/products/products_0081_8400544_to_8498477.xml
product_data/products/products_0206_17207032_to_17270551.xml
product_data/products/products_0153_13890195_to_13954269.xml
product_data/products/products_0225_18587081_to_18658601.xml
product_data/products/products_0031_3080150_to_3150841.xml
product_data/products/products_0098_10127365_to_10203898.xml
product_data/products/products_0241_19720168_to_19788467.xml
product_data/products/products_0030_3002770_to_3080141.xml
product_data/products/products_0200_16792231_to_16862496.xml
product_data/products/products_0119_11716654_to_11768312.xml
product_data/products/products_0186_15902481_to_15963138.xml
product_data/products/products_0140_12867962_to_12951264.xml
product_data/products/products_0221_18274281_to_18353927.xml
product_data/products/products_0240_19657984_to_19720159.xml
product_data/products/products_0024_2537375_to_2610448.xml
product_data/products/products_0165_14626648_to_14689964.xml
product_data/products/products_0175_15226015_to_15282775.xml
product_data/products/products_0004_606428_to_722720.xml
product_data/products/products_0198_16661293_to_16725475.xml
product_data/products/products_0156_14073254_to_14134894.xml
product_data/products/products_0111_11127354_to_11203208.xml
product_data/products/products_0137_12694711_to_12748814.xml
product_data/products/products_0044_4133529_to_4230558.xml
product_data/products/products_0138_12748823_to_12810586.xml

In [14]:
!mv product_data /content/drive/MyDrive/bestbuy

mv: inter-device move failed: 'product_data' to '/content/drive/MyDrive/bestbuy/product_data'; unable to remove target: Directory not empty

In [15]:
!ls /content/drive/MyDrive/bestbuy/product_data/categories

categories_0001_abcat0010000_to_pcmcat99300050000.xml

In [16]:
import pandas as pd

In [17]:
cat_from_xml = pd.read_xml("/content/drive/MyDrive/bestbuy/product_data/categories/categories_0001_abcat0010000_to_pcmcat99300050000.xml")

In [18]:
import xml.etree.cElementTree as et
from xml.etree import ElementTree

In [19]:
cat_file = "categories_0001_abcat0010000_to_pcmcat99300050000.xml"
tree: ElementTree = et.parse(f"/content/drive/MyDrive/bestbuy/product_data/categories/{cat_file}")

In [20]:
root = tree.getroot()

for node in root.findall("./category/path/category/[id='cat00000']"):
    print(node.findall("./name")[0].text)
    break

Best Buy

In [21]:
cat_from_xml.loc[0:4]

             id                name  path  subCategories
0  abcat0010000         Gift Center   NaN            NaN
1  abcat0011000                 Her   NaN            NaN
2  abcat0011001       Leisure Gifts   NaN            NaN
3  abcat0011002  Kitchen Essentials   NaN            NaN
4  abcat0011003         Electronics   NaN            NaN

In [22]:
!head train.csv -n 3

user,sku,category,query,click_time,query_time
000000df17cd56a5df4a94074e133c9d4739fae3,2125233,abcat0101001,"Televisiones Panasonic  50 pulgadas","2011-09-01 23:44:52.533","2011-09-01 23:43:59.752"
000001928162247ffaf63185cd8b2a244c78e7c6,2009324,abcat0101001,Sharp,"2011-09-05 12:25:37.42","2011-09-05 12:25:01.187"

In [23]:
!cat train.csv | cut -f 3 -d ',' | sort | uniq -c | sort -n -r -k 1 | head

 177638 cat02015
  80213 abcat0101001
  79245 pcmcat247400050000
  74258 pcmcat209000050008
  43991 pcmcat144700050004
  39682 pcmcat209400050001
  29809 abcat0703002
  27458 pcmcat247400050001
  25807 abcat0201011
  25132 pcmcat209000050007

In [24]:
import pandas as pd

In [25]:
train = pd.read_csv("train.csv", parse_dates=["click_time", "query_time"])
train.head()

,user,sku,category,query,click_time,query_time
0,000000df17cd56a5df4a94074e133c9d4739fae3,2125233,abcat0101001,Televisiones Panasonic 50 pulgadas,2011-09-01 23:44:52.533,2011-09-01 23:43:59.752
1,000001928162247ffaf63185cd8b2a244c78e7c6,2009324,abcat0101001,Sharp,2011-09-05 12:25:37.420,2011-09-05 12:25:01.187
2,000017f79c2b5da56721f22f9fdd726b13daf8e8,1517163,pcmcat193100050014,nook,2011-08-24 12:56:58.910,2011-08-24 12:55:13.012
3,000017f79c2b5da56721f22f9fdd726b13daf8e8,2877125,abcat0101001,rca,2011-10-25 07:18:14.722,2011-10-25 07:16:51.759
4,000017f79c2b5da56721f22f9fdd726b13daf8e8,2877134,abcat0101005,rca,2011-10-25 07:19:51.697,2011-10-25 07:16:51.759

In [26]:
test = pd.read_csv("test.csv", parse_dates=["click_time", "query_time"])
test.head()

,user,category,query,click_time,query_time
0,000000df17cd56a5df4a94074e133c9d4739fae3,pcmcat143200050016,Televisiones,2011-09-01 23:43:01.633,2011-09-01 23:42:31.317
1,000013538bfdb3c1d1f286e889113024878f3159,pcmcat194500050007,xm,2011-10-25 23:58:12.574,2011-10-25 23:57:14.409
2,000017f79c2b5da56721f22f9fdd726b13daf8e8,pcmcat193100050014,nook,2011-08-24 12:56:22.104,2011-08-24 12:55:13.012
3,0000206ed2d68b4c0e2361253da71325a74c82ba,abcat0515040,altec lansing,2011-10-25 21:01:25.854,2011-10-25 21:01:04.103
4,000020752d9ea7b2cf7ffd61e84c386711fdf267,cat02015,phantom of the opera,2011-10-23 09:46:20.915,2011-10-23 09:45:27.633

In [27]:
len(train)

1865269

In [28]:
train.loc[0:4]

,user,sku,category,query,click_time,query_time
0,000000df17cd56a5df4a94074e133c9d4739fae3,2125233,abcat0101001,Televisiones Panasonic 50 pulgadas,2011-09-01 23:44:52.533,2011-09-01 23:43:59.752
1,000001928162247ffaf63185cd8b2a244c78e7c6,2009324,abcat0101001,Sharp,2011-09-05 12:25:37.420,2011-09-05 12:25:01.187
2,000017f79c2b5da56721f22f9fdd726b13daf8e8,1517163,pcmcat193100050014,nook,2011-08-24 12:56:58.910,2011-08-24 12:55:13.012
3,000017f79c2b5da56721f22f9fdd726b13daf8e8,2877125,abcat0101001,rca,2011-10-25 07:18:14.722,2011-10-25 07:16:51.759
4,000017f79c2b5da56721f22f9fdd726b13daf8e8,2877134,abcat0101005,rca,2011-10-25 07:19:51.697,2011-10-25 07:16:51.759

In [29]:
train['time_diff'] = train['click_time'] - train['query_time']

In [30]:
train.loc[0:4]

,user,sku,category,query,click_time,query_time,time_diff
0,000000df17cd56a5df4a94074e133c9d4739fae3,2125233,abcat0101001,Televisiones Panasonic 50 pulgadas,2011-09-01 23:44:52.533,2011-09-01 23:43:59.752,0 days 00:00:52.781000
1,000001928162247ffaf63185cd8b2a244c78e7c6,2009324,abcat0101001,Sharp,2011-09-05 12:25:37.420,2011-09-05 12:25:01.187,0 days 00:00:36.233000
2,000017f79c2b5da56721f22f9fdd726b13daf8e8,1517163,pcmcat193100050014,nook,2011-08-24 12:56:58.910,2011-08-24 12:55:13.012,0 days 00:01:45.898000
3,000017f79c2b5da56721f22f9fdd726b13daf8e8,2877125,abcat0101001,rca,2011-10-25 07:18:14.722,2011-10-25 07:16:51.759,0 days 00:01:22.963000
4,000017f79c2b5da56721f22f9fdd726b13daf8e8,2877134,abcat0101005,rca,2011-10-25 07:19:51.697,2011-10-25 07:16:51.759,0 days 00:02:59.938000

In [31]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1865269 entries, 0 to 1865268
Data columns (total 7 columns):
 #   Column      Dtype
---  ------      -----
 0   user        object
 1   sku         int64
 2   category    object
 3   query       object
 4   click_time  datetime64[ns]
 5   query_time  datetime64[ns]
 6   time_diff   timedelta64[ns]
dtypes: datetime64[ns](2), int64(1), object(3), timedelta64[ns](1)
memory usage: 99.6+ MB

In [32]:
train.groupby("category").count().head()

              user  sku  query  click_time  query_time  time_diff
category
None            63   63     63          63          63         63
abcat0011000    16   16     16          16          16         16
abcat0020000     1    1      1           1           1          1
abcat0020004     3    3      3           3           3          3
abcat0031100    34   34     34          34          34         34

In [33]:
train[train.columns[2]].head()

0          abcat0101001
1          abcat0101001
2    pcmcat193100050014
3          abcat0101001
4          abcat0101005
Name: category, dtype: object

In [34]:
train["category"].value_counts().head()

cat02015              177638
abcat0101001           80213
pcmcat247400050000     79245
pcmcat209000050008     74258
pcmcat144700050004     43991
Name: category, dtype: int64

In [35]:
train["time_to_click"] = train["click_time"] - train["query_time"]

In [36]:
train.head()

,user,sku,category,query,click_time,query_time,time_diff,time_to_click
0,000000df17cd56a5df4a94074e133c9d4739fae3,2125233,abcat0101001,Televisiones Panasonic 50 pulgadas,2011-09-01 23:44:52.533,2011-09-01 23:43:59.752,0 days 00:00:52.781000,0 days 00:00:52.781000
1,000001928162247ffaf63185cd8b2a244c78e7c6,2009324,abcat0101001,Sharp,2011-09-05 12:25:37.420,2011-09-05 12:25:01.187,0 days 00:00:36.233000,0 days 00:00:36.233000
2,000017f79c2b5da56721f22f9fdd726b13daf8e8,1517163,pcmcat193100050014,nook,2011-08-24 12:56:58.910,2011-08-24 12:55:13.012,0 days 00:01:45.898000,0 days 00:01:45.898000
3,000017f79c2b5da56721f22f9fdd726b13daf8e8,2877125,abcat0101001,rca,2011-10-25 07:18:14.722,2011-10-25 07:16:51.759,0 days 00:01:22.963000,0 days 00:01:22.963000
4,000017f79c2b5da56721f22f9fdd726b13daf8e8,2877134,abcat0101005,rca,2011-10-25 07:19:51.697,2011-10-25 07:16:51.759,0 days 00:02:59.938000,0 days 00:02:59.938000

In [37]:
train.groupby("sku")["user"].count()

sku
43900               2
48530               5
127687              8
150115              1
185230              4
                   ..
9999168800050004    6
9999168800050005    3
9999168800050006    8
9999168900050003    1
9999169100050029    2
Name: user, Length: 69858, dtype: int64

In [38]:
train["time_to_click"].describe()

count                      1865269
mean     0 days 00:01:16.906892420
std      0 days 00:01:09.998017457
min         0 days 00:00:00.008000
25%         0 days 00:00:24.210000
50%         0 days 00:00:51.289000
75%         0 days 00:01:48.688000
max         0 days 00:04:59.999000
Name: time_to_click, dtype: object

In [39]:
!ls

bestbuy.zip  popular_skus.csv  product_data	 product_data.tar.gz  test.csv
drive	     popular_skus.py   product_data.tar  sample_data	      train.csv

In [40]:
!gunzip product_data.tar.gz

gzip: product_data.tar already exists; do you wish to overwrite (y or n)? n
	not overwritten

In [41]:
!tar xvf product_data.tar

product_data/
product_data/categories/
product_data/categories/categories_0001_abcat0010000_to_pcmcat99300050000.xml
product_data/reviews/
product_data/reviews/reviews_0010_1906234_to_2063675.xml
product_data/reviews/reviews_0012_2151940_to_2284992.xml
product_data/reviews/reviews_0037_6889364_to_6950068.xml
product_data/reviews/reviews_0004_501835_to_691133.xml
product_data/reviews/reviews_0018_4017769_to_4160192.xml
product_data/reviews/reviews_0007_1117796_to_1382936.xml
product_data/reviews/reviews_0016_3197161_to_3395314.xml
product_data/reviews/reviews_0027_5806868_to_6022633.xml
product_data/reviews/reviews_0014_2440655_to_2799035.xml
product_data/reviews/reviews_0015_2799189_to_3197154.xml
product_data/reviews/reviews_0021_4286995_to_4472320.xml
product_data/reviews/reviews_0024_5130266_to_5247642.xml
product_data/reviews/reviews_0035_6701490_to_6801194.xml
product_data/reviews/reviews_0005_691144_to_831905.xml
product_data/reviews/reviews_0022_4472324_to_4833387.xml
product_data/reviews/reviews_0023_4833425_to_5130263.xml
product_data/reviews/reviews_0011_2063679_to_2151936.xml
product_data/reviews/reviews_0017_3395388_to_4017768.xml
product_data/reviews/reviews_0003_345248_to_501823.xml
product_data/reviews/reviews_0025_5247643_to_5363104.xml
product_data/reviews/reviews_0006_831928_to_1117787.xml
product_data/reviews/reviews_0020_4209473_to_4286992.xml
product_data/reviews/reviews_0045_7736346_to_7762248.xml
product_data/reviews/reviews_0043_7479787_to_7610126.xml
product_data/reviews/reviews_0036_6801200_to_6889357.xml
product_data/reviews/reviews_0041_7269649_to_7387421.xml
product_data/reviews/reviews_0019_4160194_to_4209454.xml
product_data/reviews/reviews_0030_6358125_to_6396149.xml
product_data/reviews/reviews_0040_7198571_to_7269645.xml
product_data/reviews/reviews_0026_5363109_to_5806838.xml
product_data/reviews/reviews_0044_7610127_to_7736345.xml
product_data/reviews/reviews_0028_6022641_to_6172272.xml
product_data/reviews/reviews_0033_6486865_to_6587831.xml
product_data/reviews/reviews_0001_24122_to_98772.xml
product_data/reviews/reviews_0013_2285000_to_2440628.xml
product_data/reviews/reviews_0039_7039382_to_7198559.xml
product_data/reviews/reviews_0002_98780_to_345240.xml
product_data/reviews/reviews_0034_6587839_to_6701463.xml
product_data/reviews/reviews_0032_6423025_to_6486864.xml
product_data/reviews/reviews_0042_7387427_to_7479780.xml
product_data/reviews/reviews_0038_6950072_to_7039369.xml
product_data/reviews/reviews_0031_6396154_to_6423017.xml
product_data/reviews/reviews_0009_1597878_to_1906168.xml
product_data/reviews/reviews_0029_6172275_to_6358111.xml
product_data/reviews/reviews_0008_1382981_to_1597862.xml
product_data/products/
product_data/products/products_0135_12585295_to_12641439.xml
product_data/products/products_0154_13954278_to_14012757.xml
product_data/products/products_0085_8771938_to_8856419.xml
product_data/products/products_0018_2035443_to_2098517.xml
product_data/products/products_0045_4230576_to_4326232.xml
product_data/products/products_0049_4725587_to_4810643.xml
product_data/products/products_0117_11594447_to_11666315.xml
product_data/products/products_0127_12146297_to_12201565.xml
product_data/products/products_0130_12309664_to_12363186.xml
product_data/products/products_0246_20069161_to_20128686.xml
product_data/products/products_0236_19379882_to_19452187.xml
product_data/products/products_0235_19312288_to_19379873.xml
product_data/products/products_0108_10888907_to_10972432.xml
product_data/products/products_0183_15706595_to_15778623.xml
product_data/products/products_0056_5412252_to_5573998.xml
product_data/products/products_0230_18957618_to_19040862.xml
product_data/products/products_0115_11436494_to_11514097.xml
product_data/products/products_0197_16592224_to_16661284.xml
product_data/products/products_0026_2685115_to_2762861.xml
product_data/products/products_0217_17990532_to_18069368.xml
product_data/products/products_0065_6685928_to_6785115.xml
product_data/products/products_0255_9999141300050003_to_9999184200050032.xml
product_data/products/products_0068_6976034_to_7062867.xml
product_data/products/products_0182_15635699_to_15706586.xml
product_data/products/products_0020_2180446_to_2282074.xml
product_data/products/products_0120_11768321_to_11821246.xml
product_data/products/products_0159_14273724_to_14333777.xml
product_data/products/products_0106_10740362_to_10811357.xml
product_data/products/products_0176_15282784_to_15339108.xml
product_data/products/products_0016_1841154_to_1937676.xml
product_data/products/products_0046_4326241_to_4516198.xml
product_data/products/products_0219_18138409_to_18197069.xml
product_data/products/products_0143_13084146_to_13158058.xml
product_data/products/products_0249_20259278_to_20333085.xml
product_data/products/products_0054_5196931_to_5288949.xml
product_data/products/products_0252_20459355_to_999928600050002.xml
product_data/products/products_0042_3952217_to_4040683.xml
product_data/products/products_0187_15963147_to_16028923.xml
product_data/products/products_0223_18434995_to_18509097.xml
product_data/products/products_0224_18509103_to_18587072.xml
product_data/products/products_0166_14689973_to_14754722.xml
product_data/products/products_0146_13328785_to_13417778.xml
product_data/products/products_0227_18733993_to_18807545.xml
product_data/products/products_0237_19452196_to_19524448.xml
product_data/products/products_0096_9825321_to_9942574.xml
product_data/products/products_0061_6089573_to_6167961.xml
product_data/products/products_0214_17777005_to_17842836.xml
product_data/products/products_0254_999994800050007_to_9999141300050002.xml
product_data/products/products_0041_3868528_to_3952208.xml
product_data/products/products_0104_10590826_to_10667851.xml
product_data/products/products_0059_5929953_to_6014733.xml
product_data/products/products_0062_6167989_to_6299917.xml
product_data/products/products_0066_6785124_to_6877613.xml
product_data/products/products_0089_9123281_to_9216485.xml
product_data/products/products_0075_7767767_to_7873009.xml
product_data/products/products_0102_10436842_to_10511243.xml
product_data/products/products_0180_15514668_to_15571659.xml
product_data/products/products_0216_17913402_to_17990523.xml
product_data/products/products_0114_11358997_to_11436485.xml
product_data/products/products_0023_2459798_to_2537366.xml
product_data/products/products_0092_9393373_to_9489038.xml
product_data/products/products_0144_13158067_to_13245954.xml
product_data/products/products_0034_3328759_to_3408351.xml
product_data/products/products_0174_15166918_to_15226006.xml
product_data/products/products_0071_7281318_to_7425574.xml
product_data/products/products_0232_19108675_to_19176217.xml
product_data/products/products_0213_17695905_to_17776998.xml
product_data/products/products_0131_12363195_to_12418261.xml
product_data/products/products_0091_9305682_to_9393364.xml
product_data/products/products_0124_11982535_to_12038831.xml
product_data/products/products_0083_8588432_to_8680233.xml
product_data/products/products_0072_7425583_to_7565182.xml
product_data/products/products_0251_20397415_to_20459346.xml
product_data/products/products_0052_4959708_to_5051409.xml
product_data/products/products_0043_4040692_to_4133508.xml
product_data/products/products_0178_15398366_to_15457578.xml
product_data/products/products_0128_12201574_to_12256248.xml
product_data/products/products_0051_4879787_to_4959691.xml
product_data/products/products_0194_16422248_to_16477787.xml
product_data/products/products_0101_10359694_to_10436833.xml
product_data/products/products_0029_2914154_to_3002761.xml
product_data/products/products_0094_9572839_to_9709324.xml
product_data/products/products_0079_8225397_to_8315931.xml
product_data/products/products_0107_10811366_to_10888881.xml
product_data/products/products_0157_14134901_to_14201829.xml
product_data/products/products_0064_6448276_to_6685919.xml
product_data/products/products_0084_8680242_to_8771929.xml
product_data/products/products_0047_4516223_to_4625542.xml
product_data/products/products_0228_18807554_to_18879796.xml
product_data/products/products_0145_13245963_to_13328776.xml
product_data/products/products_0204_17065293_to_17144323.xml
product_data/products/products_0036_3476045_to_3543767.xml
product_data/products/products_0190_16164311_to_16238108.xml
product_data/products/products_0167_14754731_to_14825692.xml
product_data/products/products_0055_5288951_to_5412243.xml
product_data/products/products_0248_20193324_to_20259269.xml
product_data/products/products_0097_9942583_to_10127329.xml
product_data/products/products_0155_14012766_to_14073245.xml
product_data/products/products_0011_1304779_to_1387582.xml
product_data/products/products_0168_14825709_to_14881826.xml
product_data/products/products_0181_15571668_to_15635671.xml
product_data/products/products_0053_5051427_to_5196922.xml
product_data/products/products_0033_3239757_to_3328731.xml
product_data/products/products_0192_16295821_to_16351387.xml
product_data/products/products_0129_12256275_to_12309655.xml
product_data/products/products_0027_2762943_to_2840956.xml
product_data/products/products_0242_19788476_to_19863856.xml
product_data/products/products_0121_11821255_to_11872048.xml
product_data/products/products_0069_7062876_to_7193262.xml
product_data/products/products_0019_2098526_to_2180438.xml
product_data/products/products_0136_12641448_to_12694701.xml
product_data/products/products_0035_3408360_to_3476039.xml
product_data/products/products_0087_8944798_to_9037801.xml
product_data/products/products_0014_1572108_to_1742733.xml
product_data/products/products_0074_7675401_to_7767749.xml
product_data/products/products_0038_3618062_to_3691856.xml
product_data/products/products_0234_19241696_to_19312279.xml
product_data/products/products_0058_5749951_to_5929944.xml
product_data/products/products_0067_6877702_to_6976025.xml
product_data/products/products_0050_4810661_to_4879784.xml
product_data/products/products_0202_16928194_to_16996609.xml
product_data/products/products_0105_10667904_to_10740353.xml
product_data/products/products_0164_14567104_to_14626639.xml
product_data/products/products_0212_17616037_to_17695898.xml
product_data/products/products_0147_13417787_to_13491018.xml
product_data/products/products_0132_12418271_to_12472121.xml
product_data/products/products_0032_3150850_to_3239748.xml
product_data/products/products_0253_999928700050000_to_999994800050006.xml
product_data/products/products_0162_14450603_to_14508213.xml
product_data/products/products_0243_19863865_to_19939021.xml
product_data/products/products_0113_11280712_to_11358988.xml
product_data/products/products_0012_1387591_to_1471909.xml
product_data/products/products_0218_18069377_to_18138392.xml
product_data/products/products_0025_2610464_to_2685106.xml
product_data/products/products_0199_16725484_to_16792222.xml
product_data/products/products_0173_15110256_to_15166909.xml
product_data/products/products_0171_14997042_to_15053763.xml
product_data/products/products_0009_1156156_to_1230126.xml
product_data/products/products_0028_2840965_to_2914145.xml
product_data/products/products_0239_19595739_to_19657975.xml
product_data/products/products_0203_16996618_to_17065284.xml
product_data/products/products_0010_1230144_to_1304774.xml
product_data/products/products_0169_14881835_to_14939034.xml
product_data/products/products_0179_15457587_to_15514659.xml
product_data/products/products_0247_20128695_to_20193315.xml
product_data/products/products_0003_518229_to_606384.xml
product_data/products/products_0133_12472139_to_12528669.xml
product_data/products/products_0188_16028932_to_16101086.xml
product_data/products/products_0112_11203235_to_11280696.xml
product_data/products/products_0076_7873018_to_7969638.xml
product_data/products/products_0088_9037829_to_9123272.xml
product_data/products/products_0063_6299926_to_6448267.xml
product_data/products/products_0215_17842845_to_17913395.xml
product_data/products/products_0015_1742742_to_1841136.xml
product_data/products/products_0195_16477796_to_16533333.xml
product_data/products/products_0040_3781991_to_3868519.xml
product_data/products/products_0070_7193271_to_7281309.xml
product_data/products/products_0238_19524457_to_19595711.xml
product_data/products/products_0170_14939043_to_14997033.xml
product_data/products/products_0158_14201838_to_14273715.xml
product_data/products/products_0110_11054235_to_11127345.xml
product_data/products/products_0007_1002897_to_1067124.xml
product_data/products/products_0021_2282078_to_2380024.xml
product_data/products/products_0122_11872057_to_11922459.xml
product_data/products/products_0109_10972441_to_11054226.xml
product_data/products/products_0209_17399325_to_17465752.xml
product_data/products/products_0139_12810595_to_12867953.xml
product_data/products/products_0048_4625551_to_4725585.xml
product_data/products/products_0207_17270579_to_17335288.xml
product_data/products/products_0201_16862502_to_16928185.xml
product_data/products/products_0210_17465761_to_17538942.xml
product_data/products/products_0256_9999184200050033_to_9999186400050044.xml
product_data/products/products_0082_8498486_to_8588414.xml
product_data/products/products_0142_13024309_to_13084137.xml
product_data/products/products_0172_15053772_to_15110247.xml
product_data/products/products_0125_12038841_to_12092381.xml
product_data/products/products_0208_17335297_to_17399316.xml
product_data/products/products_0005_722800_to_846222.xml
product_data/products/products_0086_8856428_to_8944789.xml
product_data/products/products_0008_1067160_to_1156147.xml
product_data/products/products_0078_8107452_to_8225388.xml
product_data/products/products_0001_2570_to_430420.xml
product_data/products/products_0099_10203969_to_10281018.xml
product_data/products/products_0090_9216494_to_9305673.xml
product_data/products/products_0103_10511252_to_10590817.xml
product_data/products/products_0093_9489047_to_9572811.xml
product_data/products/products_0231_19040871_to_19108666.xml
product_data/products/products_0152_13821206_to_13890186.xml
product_data/products/products_0189_16101095_to_16164302.xml
product_data/products/products_0141_12951273_to_13024292.xml
product_data/products/products_0220_18197078_to_18274272.xml
product_data/products/products_0013_1471918_to_1572104.xml
product_data/products/products_0057_5574014_to_5749942.xml
product_data/products/products_0116_11514104_to_11594438.xml
product_data/products/products_0160_14333786_to_14393578.xml
product_data/products/products_0193_16351396_to_16422239.xml
product_data/products/products_0150_13646904_to_13735238.xml
product_data/products/products_0002_430439_to_518210.xml
product_data/products/products_0126_12092399_to_12146288.xml
product_data/products/products_0233_19176226_to_19241687.xml
product_data/products/products_0123_11922468_to_11982526.xml
product_data/products/products_0250_20333094_to_20397406.xml
product_data/products/products_0222_18353936_to_18434986.xml
product_data/products/products_0077_7969647_to_8107443.xml
product_data/products/products_0060_6014751_to_6089564.xml
product_data/products/products_0134_12528678_to_12585286.xml
product_data/products/products_0196_16533342_to_16592215.xml
product_data/products/products_0006_846231_to_1002890.xml
product_data/products/products_0244_19939049_to_20004526.xml
product_data/products/products_0037_3543776_to_3618053.xml
product_data/products/products_0245_20004535_to_20069152.xml
product_data/products/products_0229_18879805_to_18957609.xml
product_data/products/products_0226_18658629_to_18733984.xml
product_data/products/products_0022_2380033_to_2459734.xml
product_data/products/products_0039_3691865_to_3781982.xml
product_data/products/products_0100_10281045_to_10359676.xml
product_data/products/products_0149_13563477_to_13646897.xml
product_data/products/products_0177_15339117_to_15398357.xml
product_data/products/products_0191_16238796_to_16295812.xml
product_data/products/products_0080_8315959_to_8400517.xml
product_data/products/products_0163_14508222_to_14567097.xml
product_data/products/products_0151_13735247_to_13821199.xml
product_data/products/products_0211_17538951_to_17616028.xml
product_data/products/products_0184_15778632_to_15842484.xml
product_data/products/products_0118_11666324_to_11716645.xml
product_data/products/products_0161_14393587_to_14450596.xml
product_data/products/products_0073_7565379_to_7675367.xml
product_data/products/products_0017_1937685_to_2035434.xml
product_data/products/products_0185_15842493_to_15902472.xml
product_data/products/products_0148_13491027_to_13563468.xml
product_data/products/products_0095_9709333_to_9825279.xml
product_data/products/products_0205_17144332_to_17207023.xml
product_data/products/products_0081_8400544_to_8498477.xml
product_data/products/products_0206_17207032_to_17270551.xml
product_data/products/products_0153_13890195_to_13954269.xml
product_data/products/products_0225_18587081_to_18658601.xml
product_data/products/products_0031_3080150_to_3150841.xml
product_data/products/products_0098_10127365_to_10203898.xml
product_data/products/products_0241_19720168_to_19788467.xml
product_data/products/products_0030_3002770_to_3080141.xml
product_data/products/products_0200_16792231_to_16862496.xml
product_data/products/products_0119_11716654_to_11768312.xml
product_data/products/products_0186_15902481_to_15963138.xml
product_data/products/products_0140_12867962_to_12951264.xml
product_data/products/products_0221_18274281_to_18353927.xml
product_data/products/products_0240_19657984_to_19720159.xml
product_data/products/products_0024_2537375_to_2610448.xml
product_data/products/products_0165_14626648_to_14689964.xml
product_data/products/products_0175_15226015_to_15282775.xml
product_data/products/products_0004_606428_to_722720.xml
product_data/products/products_0198_16661293_to_16725475.xml
product_data/products/products_0156_14073254_to_14134894.xml
product_data/products/products_0111_11127354_to_11203208.xml
product_data/products/products_0137_12694711_to_12748814.xml
product_data/products/products_0044_4133529_to_4230558.xml
product_data/products/products_0138_12748823_to_12810586.xml

In [42]:
pdata = pd.read_xml("product_data/products/products_0138_12748823_to_12810586.xml")

In [43]:
pdata.head()

,sku,productId,name,source,type,startDate,new,active,activeUpdateDate,regularPrice,...,lengthInMinutes,mpaaRating,plot,plotHtml,studio,theatricalReleaseDate,relatedCinemaNowId,relatedCinemaNowUrl,cast,crew
0,12748823,298680,Earth Incarnation - CD,bestbuy,Music,1996-07-10,False,False,2012-07-03T02:39:02,14.99,...,NaN,None,None,None,None,NaN,NaN,NaN,NaN,NaN
1,12748832,132973,Searching for the Trail - CD,bestbuy,Music,1996-07-10,False,False,2012-07-03T03:05:42,14.99,...,NaN,None,None,None,None,NaN,NaN,NaN,NaN,NaN
2,12748841,265428,Toutou - CD,bestbuy,Music,1997-04-22,False,False,2012-07-02T20:31:54,22.99,...,NaN,None,None,None,None,NaN,NaN,NaN,NaN,NaN
3,12748851,85416,Know Jah Better - CASSETTE,bestbuy,Music,1997-07-02,False,False,2012-07-03T03:55:44,8.99,...,NaN,None,None,None,None,NaN,NaN,NaN,NaN,NaN
4,12748869,257749,Meditations: Reggae Crazy 71-79 - Various - CD,bestbuy,Music,1997-03-04,False,False,2012-07-02T23:01:17,14.99,...,NaN,None,None,None,None,NaN,NaN,NaN,NaN,NaN

In [44]:
train.head()

,user,sku,category,query,click_time,query_time,time_diff,time_to_click
0,000000df17cd56a5df4a94074e133c9d4739fae3,2125233,abcat0101001,Televisiones Panasonic 50 pulgadas,2011-09-01 23:44:52.533,2011-09-01 23:43:59.752,0 days 00:00:52.781000,0 days 00:00:52.781000
1,000001928162247ffaf63185cd8b2a244c78e7c6,2009324,abcat0101001,Sharp,2011-09-05 12:25:37.420,2011-09-05 12:25:01.187,0 days 00:00:36.233000,0 days 00:00:36.233000
2,000017f79c2b5da56721f22f9fdd726b13daf8e8,1517163,pcmcat193100050014,nook,2011-08-24 12:56:58.910,2011-08-24 12:55:13.012,0 days 00:01:45.898000,0 days 00:01:45.898000
3,000017f79c2b5da56721f22f9fdd726b13daf8e8,2877125,abcat0101001,rca,2011-10-25 07:18:14.722,2011-10-25 07:16:51.759,0 days 00:01:22.963000,0 days 00:01:22.963000
4,000017f79c2b5da56721f22f9fdd726b13daf8e8,2877134,abcat0101005,rca,2011-10-25 07:19:51.697,2011-10-25 07:16:51.759,0 days 00:02:59.938000,0 days 00:02:59.938000

In [96]:
train = pd.read_csv("train.csv", parse_dates=["click_time", "query_time"])
train.head()

,user,sku,category,query,click_time,query_time
0,000000df17cd56a5df4a94074e133c9d4739fae3,2125233,abcat0101001,Televisiones Panasonic 50 pulgadas,2011-09-01 23:44:52.533,2011-09-01 23:43:59.752
1,000001928162247ffaf63185cd8b2a244c78e7c6,2009324,abcat0101001,Sharp,2011-09-05 12:25:37.420,2011-09-05 12:25:01.187
2,000017f79c2b5da56721f22f9fdd726b13daf8e8,1517163,pcmcat193100050014,nook,2011-08-24 12:56:58.910,2011-08-24 12:55:13.012
3,000017f79c2b5da56721f22f9fdd726b13daf8e8,2877125,abcat0101001,rca,2011-10-25 07:18:14.722,2011-10-25 07:16:51.759
4,000017f79c2b5da56721f22f9fdd726b13daf8e8,2877134,abcat0101005,rca,2011-10-25 07:19:51.697,2011-10-25 07:16:51.759

In [46]:
test = pd.read_csv("test.csv", parse_dates=["click_time", "query_time"])
test.head()

,user,category,query,click_time,query_time
0,000000df17cd56a5df4a94074e133c9d4739fae3,pcmcat143200050016,Televisiones,2011-09-01 23:43:01.633,2011-09-01 23:42:31.317
1,000013538bfdb3c1d1f286e889113024878f3159,pcmcat194500050007,xm,2011-10-25 23:58:12.574,2011-10-25 23:57:14.409
2,000017f79c2b5da56721f22f9fdd726b13daf8e8,pcmcat193100050014,nook,2011-08-24 12:56:22.104,2011-08-24 12:55:13.012
3,0000206ed2d68b4c0e2361253da71325a74c82ba,abcat0515040,altec lansing,2011-10-25 21:01:25.854,2011-10-25 21:01:04.103
4,000020752d9ea7b2cf7ffd61e84c386711fdf267,cat02015,phantom of the opera,2011-10-23 09:46:20.915,2011-10-23 09:45:27.633

Train & Test **Data**

In [47]:
from urllib import parse
import xmltodict, json

In [48]:
with open(f"/content/drive/MyDrive/bestbuy/product_data/categories/{cat_file}", 'r') as cat:
  CatData = xmltodict.parse(cat.read())
  data = json.loads(json.dumps(CatData))
  categories = data["categories"].get("category")

In [49]:
for x in range(5):
  levels = ['category_l1', 'category_l2',
            'category_l3', 'category_l4',
            'category_l5']
  train[levels] = ''
  test[levels] = ''

In [50]:
test.head()

,user,category,query,click_time,query_time,category_l1,category_l2,category_l3,category_l4,category_l5
0,000000df17cd56a5df4a94074e133c9d4739fae3,pcmcat143200050016,Televisiones,2011-09-01 23:43:01.633,2011-09-01 23:42:31.317,,,,,
1,000013538bfdb3c1d1f286e889113024878f3159,pcmcat194500050007,xm,2011-10-25 23:58:12.574,2011-10-25 23:57:14.409,,,,,
2,000017f79c2b5da56721f22f9fdd726b13daf8e8,pcmcat193100050014,nook,2011-08-24 12:56:22.104,2011-08-24 12:55:13.012,,,,,
3,0000206ed2d68b4c0e2361253da71325a74c82ba,abcat0515040,altec lansing,2011-10-25 21:01:25.854,2011-10-25 21:01:04.103,,,,,
4,000020752d9ea7b2cf7ffd61e84c386711fdf267,cat02015,phantom of the opera,2011-10-23 09:46:20.915,2011-10-23 09:45:27.633,,,,,

In [51]:
train.head()

,user,sku,category,query,click_time,query_time,category_l1,category_l2,category_l3,category_l4,category_l5
0,000000df17cd56a5df4a94074e133c9d4739fae3,2125233,abcat0101001,Televisiones Panasonic 50 pulgadas,2011-09-01 23:44:52.533,2011-09-01 23:43:59.752,,,,,
1,000001928162247ffaf63185cd8b2a244c78e7c6,2009324,abcat0101001,Sharp,2011-09-05 12:25:37.420,2011-09-05 12:25:01.187,,,,,
2,000017f79c2b5da56721f22f9fdd726b13daf8e8,1517163,pcmcat193100050014,nook,2011-08-24 12:56:58.910,2011-08-24 12:55:13.012,,,,,
3,000017f79c2b5da56721f22f9fdd726b13daf8e8,2877125,abcat0101001,rca,2011-10-25 07:18:14.722,2011-10-25 07:16:51.759,,,,,
4,000017f79c2b5da56721f22f9fdd726b13daf8e8,2877134,abcat0101005,rca,2011-10-25 07:19:51.697,2011-10-25 07:16:51.759,,,,,

In [105]:
def bestbuy_category(index:int):
  level = ''
  if index == 0:
    level = "category_l1"
  elif index == 1:
    level = "category_l2"
  elif index == 2:
    level = "category_l3"
  elif index == 3:
    level = "category_l4"
  elif index == 4:
    level = "category_l5"
  return level

In [107]:
for cat in categories[:50]:
    path = cat.get("path")
    id = cat.get("id")
    address = path.get("category")

    counter = 0
    index = 0

    for i in range(len(address)):
      lvl = bestbuy_category(counter)
      
      try:
        cat_id =  address[i]["id"]

        if index <= 5: 
          train.loc[train['category'] == id, lvl] = cat_id
          test.loc[test['category'] == id, lvl] = cat_id
          index = index + 1
          counter = counter + 1

        if cat_id == id:
          for i in range(5 - counter):
            lvl = bestbuy_category(counter)
            if index <= 5: 
              train.loc[train['category'] == id, lvl] = ""
              test.loc[test['category'] == id, lvl] = ""
              index = index + 1

      except KeyError as key:
        print(key)

In [103]:
train.head(50)

,user,sku,category,query,click_time,query_time,category_l1,category_l2,category_l3,category_l4,category_l5
0,000000df17cd56a5df4a94074e133c9d4739fae3,2125233,abcat0101001,Televisiones Panasonic 50 pulgadas,2011-09-01 23:44:52.533,2011-09-01 23:43:59.752,cat00000,abcat0100000,abcat0101000,abcat0101001,
1,000001928162247ffaf63185cd8b2a244c78e7c6,2009324,abcat0101001,Sharp,2011-09-05 12:25:37.420,2011-09-05 12:25:01.187,cat00000,abcat0100000,abcat0101000,abcat0101001,
2,000017f79c2b5da56721f22f9fdd726b13daf8e8,1517163,pcmcat193100050014,nook,2011-08-24 12:56:58.910,2011-08-24 12:55:13.012,NaN,NaN,NaN,NaN,NaN
3,000017f79c2b5da56721f22f9fdd726b13daf8e8,2877125,abcat0101001,rca,2011-10-25 07:18:14.722,2011-10-25 07:16:51.759,cat00000,abcat0100000,abcat0101000,abcat0101001,
4,000017f79c2b5da56721f22f9fdd726b13daf8e8,2877134,abcat0101005,rca,2011-10-25 07:19:51.697,2011-10-25 07:16:51.759,cat00000,abcat0100000,abcat0101000,abcat0101005,
5,00001ff8394a2d9bd7adffb1547180bf5bbfc4e5,2416092,pcmcat143200050016,Flat screen tvs,2011-09-07 15:54:47.956,2011-09-07 15:53:24.353,NaN,NaN,NaN,NaN,NaN
6,000027e2f86b55c901882a9d47ac7feec964825d,3108172,pcmcat247400050001,macbook,2011-09-25 11:07:02.603,2011-09-25 11:05:26.996,NaN,NaN,NaN,NaN,NaN
7,0000323223cd657f7e063ddb83f32b332d46e920,2264036,pcmcat171900050028,Blue tooth headphones,2011-09-23 12:40:20.871,2011-09-23 12:40:14.845,NaN,NaN,NaN,NaN,NaN
8,00003cb3f85244c652f22c1daf11aed35d5ab7f6,8280834,abcat0107004,Tv antenna,2011-08-29 13:37:32.903,2011-08-29 13:33:23.249,NaN,NaN,NaN,NaN,NaN
9,0000404374364b75c80d384c2a8c1d379237a2d9,2740208,pcmcat186100050006,memory card,2011-10-25 22:55:58.683,2011-10-25 22:54:45.926,NaN,NaN,NaN,NaN,NaN
10,0000517733c9766b4eeef84f2eb8720b3af3233f,2584273,pcmcat138100050040,AC power cord,2011-09-11 12:48:44.139,2011-09-11 12:46:18.466,NaN,NaN,NaN,NaN,NaN
11,00006d8bb4bcc66f1676237629968277fb7a8dc5,1230537,pcmcat201900050009,Zagg iPhone,2011-10-18 17:21:33.919,2011-10-18 17:21:26.570,NaN,NaN,NaN,NaN,NaN
12,00007557d9b11f2f1a99792317963d30174171ba,3168067,cat02713,Watch The Throne,2011-09-04 10:55:20.427,2011-09-04 10:55:10.874,NaN,NaN,NaN,NaN,NaN
13,0000776d7bf35b984ca8e3671327a7ac1d07a86c,7997055,pcmcat224000050003,Remote control extender,2011-10-28 16:26:29.203,2011-10-28 16:26:20.358,NaN,NaN,NaN,NaN,NaN
14,000086ad8ef4acaa7b1624b47d981fc2f7bc8af9,2009041,pcmcat233600050006,Camcorder,2011-10-10 00:35:26.858,2011-10-10 00:34:30.708,NaN,NaN,NaN,NaN,NaN
15,0000870469b85f38ceba4b1add61419eb8da9dc5,1988047,abcat0707001,3ds,2011-09-23 22:14:08.965,2011-09-23 22:13:37.430,NaN,NaN,NaN,NaN,NaN
16,0000aed826178a7929389c0c3d68bd0124c3dec1,1686079,abcat0410020,hoya,2011-09-10 12:04:53.645,2011-09-10 12:04:30.805,NaN,NaN,NaN,NaN,NaN
17,0000bf4a5fc3c0fc9faaef83b1048927962ef6ab,3770439,pcmcat144700050004,wireless headphones,2011-10-23 11:44:35.074,2011-10-23 11:43:27.110,NaN,NaN,NaN,NaN,NaN
18,0000bf4a5fc3c0fc9faaef83b1048927962ef6ab,2602403,pcmcat144700050004,wireless headphones,2011-10-23 11:45:24.416,2011-10-23 11:43:27.110,NaN,NaN,NaN,NaN,NaN
19,0000c4e9d7075985d1020c456e7ce36f83f834eb,2126065,abcat0101001,Samsung 40,2011-09-28 17:27:11.184,2011-09-28 17:26:15.832,cat00000,abcat0100000,abcat0101000,abcat0101001,
20,00010d7a49fb773720d7b7204f2f7375142cc126,1162439,abcat0701001,Xbox,2011-09-03 09:15:35.939,2011-09-03 09:14:36.469,NaN,NaN,NaN,NaN,NaN
21,00010d7a49fb773720d7b7204f2f7375142cc126,2303202,abcat0701001,Xbox,2011-09-03 09:16:54.654,2011-09-03 09:14:36.469,NaN,NaN,NaN,NaN,NaN
22,00010d7a49fb773720d7b7204f2f7375142cc126,1126887,pcmcat232900050029,Xbox360,2011-09-03 09:32:09.398,2011-09-03 09:31:20.142,NaN,NaN,NaN,NaN,NaN
23,00010d7a49fb773720d7b7204f2f7375142cc126,1260591,abcat0515022,Joy stick,2011-09-19 21:17:48.555,2011-09-19 21:16:49.341,NaN,NaN,NaN,NaN,NaN
24,00010d7a49fb773720d7b7204f2f7375142cc126,5876867,abcat0515023,Joy stick,2011-09-19 21:18:08.158,2011-09-19 21:16:49.341,NaN,NaN,NaN,NaN,NaN
25,00010d87c0ea748bdc1db5c6b560e84b4f380506,3425255,cat02015,Zookeeper,2011-09-06 17:14:53.023,2011-09-06 17:12:32.784,NaN,NaN,NaN,NaN,NaN
26,000126150c17acb66664a42c47d5dba399311783,9755322,pcmcat247400050001,Macbook,2011-09-26 15:12:48.533,2011-09-26 15:12:33.537,NaN,NaN,NaN,NaN,NaN
27,000126150c17acb66664a42c47d5dba399311783,2061031,pcmcat214000050002,Panasomic lumix,2011-10-06 14:54:27.202,2011-10-06 14:54:12.652,NaN,NaN,NaN,NaN,NaN
28,0001271194ff4cd582cd67c03d58f0d3938382e6,1432551,pcmcat144700050004,Ipad,2011-10-27 21:18:51.266,2011-10-27 21:17:50.033,NaN,NaN,NaN,NaN,NaN
29,00013e57905978ad8c9748b36ef33bf5b89a9cce,9132379,cat02015,anime,2011-10-26 00:42:31.404,2011-10-26 00:42:00.805,NaN,NaN,NaN,NaN,NaN
30,00014aac7ef84270dab58af1c92b79685b89b9b9,9604444,pcmcat165900050048,blue tooth,2011-10-21 18:40:56.313,2011-10-21 18:38:55.259,NaN,NaN,NaN,NaN,NaN
31,00015fd3d8c314df71a64754e220aac30aaa9b22,9770615,pcmcat166600050000,Cable management,2011-10-05 10:09:22.104,2011-10-05 10:08:26.678,NaN,NaN,NaN,NaN,NaN
32,00015fd3d8c314df71a64754e220aac30aaa9b22,8735586,pcmcat166600050000,Cable management,2011-10-05 10:09:34.283,2011-10-05 10:08:26.678,NaN,NaN,NaN,NaN,NaN
33,00015fd3d8c314df71a64754e220aac30aaa9b22,9695793,pcmcat230800050017,Cable management,2011-10-05 10:10:35.552,2011-10-05 10:08:26.678,NaN,NaN,NaN,NaN,NaN
34,000165fa12a2052cf4da7318cb4b2843b41d7a48,1092403,abcat0703002,Driver ps3,2011-09-23 18:23:42.240,2011-09-23 18:23:30.109,NaN,NaN,NaN,NaN,NaN
35,000166190f48c7610228bdb845c82c4c11871734,2417037,pcmcat195200050001,Fisheye lens,2011-09-21 06:55:39.393,2011-09-21 06:53:49.284,NaN,NaN,NaN,NaN,NaN
36,00016ac345cf3220c4f56855d7021693290796c2,9775134,abcat0302037,alpine,2011-10-07 08:07:40.295,2011-10-07 08:06:49.896,NaN,NaN,NaN,NaN,NaN
37,00016ac345cf3220c4f56855d7021693290796c2,3271964,pcmcat223000050008,punch,2011-10-07 08:11:41.056,2011-10-07 08:10:54.935,NaN,NaN,NaN,NaN,NaN
38,00016ac345cf3220c4f56855d7021693290796c2,3271982,abcat0302003,punch,2011-10-07 08:12:20.766,2011-10-07 08:10:54.935,NaN,NaN,NaN,NaN,NaN
39,00016bbb306e305d68e177ac1e22e091bf81a6e7,1125779,pcmcat232900050031,washer,2011-09-01 22:13:47.332,2011-09-01 22:13:15.762,NaN,NaN,NaN,NaN,NaN
40,00017f7beeac02736c0ce7bf1e75f3010939b34e,1831054,abcat0101001,lcd tv,2011-09-28 07:26:32.153,2011-09-28 07:26:21.476,cat00000,abcat0100000,abcat0101000,abcat0101001,
41,00018640b0978982d1acaa7649476b2f52999e53,1517163,pcmcat193100050014,tablet,2011-10-23 23:21:31.474,2011-10-23 23:19:41.601,NaN,NaN,NaN,NaN,NaN
42,000189195b3b3b0a4a02cd61d600aaa13fa01132,9894452,abcat0508009,Microsoft office,2011-09-20 17:02:55.808,2011-09-20 17:01:29.669,NaN,NaN,NaN,NaN,NaN
43,00018bd07703a3d9040ae56de3f9417edc043385,9414671,abcat0503013,Dsl router,2011-09-18 14:40:00.393,2011-09-18 14:39:36.076,NaN,NaN,NaN,NaN,NaN
44,00018bd07703a3d9040ae56de3f9417edc043385,2847643,abcat0503013,Dsl router,2011-09-18 14:42:00.007,2011-09-18 14:39:36.076,NaN,NaN,NaN,NaN,NaN
45,00018ef0bcccb5ad919cc89875c850b44fbd4c83,9557712,cat02672,Nirvana bleach,2011-09-10 18:15:06.427,2011-09-10 18:14:51.804,NaN,NaN,NaN,NaN,NaN
46,00019eb51e019034e8b666e36c06ca469c160e9e,2138389,abcat0101001,lcd tv,2011-10-09 09:58:14.524,2011-10-09 09:58:11.367,cat00000,abcat0100000,abcat0101000,abcat0101001,
47,0001aa5d7cbd50d4d73c1e34a1d21fccdc5fdede,2355091,abcat0101001,Panasonic 3d tv,2011-09-01 21:30:39.259,2011-09-01 21:28:18.776,cat00000,abcat0100000,abcat0101000,abcat0101001,
48,0001be1731ee7d1c519bc7e87110c9eb880cb396,8993388,abcat0715001,Hdmi,2011-08-31 20:20:52.635,2011-08-31 20:18:00.849,NaN,NaN,NaN,NaN,NaN
49,0001be1731ee7d1c519bc7e87110c9eb880cb396,8427106,abcat0107020,Hdmi,2011-08-31 20:22:29.411,2011-08-31 20:18:00.849,NaN,NaN,NaN,NaN,NaN

In [102]:
test.head(50)

,user,category,query,click_time,query_time,category_l1,category_l2,category_l3,category_l4,category_l5
0,000000df17cd56a5df4a94074e133c9d4739fae3,pcmcat143200050016,Televisiones,2011-09-01 23:43:01.633,2011-09-01 23:42:31.317,,,,,
1,000013538bfdb3c1d1f286e889113024878f3159,pcmcat194500050007,xm,2011-10-25 23:58:12.574,2011-10-25 23:57:14.409,,,,,
2,000017f79c2b5da56721f22f9fdd726b13daf8e8,pcmcat193100050014,nook,2011-08-24 12:56:22.104,2011-08-24 12:55:13.012,,,,,
3,0000206ed2d68b4c0e2361253da71325a74c82ba,abcat0515040,altec lansing,2011-10-25 21:01:25.854,2011-10-25 21:01:04.103,,,,,
4,000020752d9ea7b2cf7ffd61e84c386711fdf267,cat02015,phantom of the opera,2011-10-23 09:46:20.915,2011-10-23 09:45:27.633,,,,,
5,0000223fb00aa83c249b1fa18b74baed903f4277,cat02015,dazzle,2011-10-25 22:37:26.285,2011-10-25 22:36:39.379,,,,,
6,000027e2f86b55c901882a9d47ac7feec964825d,pcmcat247400050001,macbook,2011-09-25 11:07:26.847,2011-09-25 11:05:26.996,,,,,
7,00003cb3f85244c652f22c1daf11aed35d5ab7f6,abcat0107004,Tv antenna,2011-08-29 13:36:46.094,2011-08-29 13:33:23.249,,,,,
8,000040a4744f579323c0d4c0971bcc8783e79fde,cat02661,ethernet,2011-10-26 00:45:31.383,2011-10-26 00:44:15.286,,,,,
9,0000776d7bf35b984ca8e3671327a7ac1d07a86c,pcmcat224000050003,Remote control extender,2011-10-28 16:26:31.856,2011-10-28 16:26:20.358,,,,,
10,0000870469b85f38ceba4b1add61419eb8da9dc5,abcat0707001,3ds,2011-09-23 22:14:44.654,2011-09-23 22:13:37.430,,,,,
11,000097491a26c8f8b5fdf97b99a7e4e159c3bf0c,abcat0201007,HP car charger,2011-10-24 14:01:16.306,2011-10-24 14:01:07.099,,,,,
12,0000a4e6026726af06fd41cebf887260eeba1d0a,pcmcat144700050004,head phones,2011-10-15 13:20:14.837,2011-10-15 13:15:15.737,,,,,
13,0000abd036ce04605cfc444045ff66b9f1d0f0d1,abcat0101001,Samsumg 7000,2011-08-30 09:39:23.498,2011-08-30 09:38:52.898,cat00000,abcat0100000,abcat0101000,abcat0101001,
14,0000b846e71b2c8cab3d8130a64ec0e267adb2af,pcmcat209400050001,iPhone 4s,2011-10-14 23:49:05.472,2011-10-14 23:48:15.887,,,,,
15,0000bda70aeade8e4ea10c8c36175ccceff53f9d,abcat0503002,Linksys e4200,2011-08-20 05:29:32.788,2011-08-20 05:29:12.960,,,,,
16,0000bf4a5fc3c0fc9faaef83b1048927962ef6ab,pcmcat144700050004,wireless headphones,2011-10-23 11:45:58.438,2011-10-23 11:43:27.110,,,,,
17,0000db7c651e2c5a87ddcad660d12ddf5b916ae6,abcat0905001,Bosch ascenta,2011-09-10 00:49:20.956,2011-09-10 00:45:17.501,,,,,
18,0000dc29e0a5f51569eb1927b477a6698e16d0c1,pcmcat247400050000,LaborDay_Computers_20110902,2011-09-03 01:25:18.167,2011-09-03 01:24:51.252,,,,,
19,0000dc29e0a5f51569eb1927b477a6698e16d0c1,pcmcat247400050001,Mac,2011-09-03 01:27:49.552,2011-09-03 01:27:05.903,,,,,
20,0000f1fd55debe46f55da3a469cefdb20dac3f86,cat02702,prince,2011-10-26 00:39:29.064,2011-10-26 00:38:57.931,,,,,
21,0000fe6915026aa2429f00112b7fef83a51ffa29,pcmcat209700050013,anti virus,2011-10-19 23:06:39.614,2011-10-19 23:05:51.294,,,,,
22,00010d7a49fb773720d7b7204f2f7375142cc126,pcmcat247400050000,Laptops,2011-09-04 20:19:15.641,2011-09-04 20:18:49.824,,,,,
23,00010d7a49fb773720d7b7204f2f7375142cc126,pcmcat247400050000,Laptops,2011-09-04 20:20:24.107,2011-09-04 20:18:49.824,,,,,
24,00010d7a49fb773720d7b7204f2f7375142cc126,pcmcat174700050005,Flight,2011-09-19 21:15:04.954,2011-09-19 21:14:27.492,,,,,
25,00011291c9841822619874f39c5b4147aa202820,pcmcat233000050008,Nikor,2011-09-06 22:49:56.042,2011-09-06 22:48:05.722,,,,,
26,000126150c17acb66664a42c47d5dba399311783,abcat0508026,Photoshop,2011-08-17 14:03:44.277,2011-08-17 14:01:17.372,,,,,
27,00012b2e3a1238e1449b9bb1d847e3cc7048cf03,abcat0401004,kodak easyshare,2011-10-25 21:32:44.048,2011-10-25 21:31:56.759,,,,,
28,000135c9a9581672ddeb9b2bdc7d1e28cf94c124,pcmcat164800050018,roomba,2011-10-07 08:36:28.485,2011-10-07 08:31:38.322,,,,,
29,00013a91087d1adb34843336c9ac396ff1cfa93c,pcmcat161100050044,airport express,2011-10-07 09:28:52.000,2011-10-07 09:28:23.515,,,,,
30,00013f33f0819391e64e4d5b6f593137db86b07a,abcat0703002,Ps3,2011-10-02 10:54:42.273,2011-10-02 10:53:57.453,,,,,
31,00015c3e35d326967846f0ccfca7ed989b045f5b,cat02015,Captain America Blu Ray,2011-10-29 17:03:03.330,2011-10-29 17:02:32.840,,,,,
32,000163c4e33a44f86c3a4f6457d81363119ec5a4,pcmcat193100050018,cellphones,2011-10-06 23:41:55.911,2011-10-06 23:41:43.015,,,,,
33,000166190f48c7610228bdb845c82c4c11871734,pcmcat196500050012,Fisheye lens,2011-09-21 06:56:09.491,2011-09-21 06:53:49.284,,,,,
34,000166190f48c7610228bdb845c82c4c11871734,pcmcat247400050001,MacBook,2011-09-22 08:33:25.056,2011-09-22 08:31:46.924,,,,,
35,000166190f48c7610228bdb845c82c4c11871734,abcat0513006,Wacom cintiqu tablet,2011-09-23 07:28:53.329,2011-09-23 07:28:16.358,,,,,
36,00016ac345cf3220c4f56855d7021693290796c2,abcat0302003,punch,2011-10-07 08:12:06.180,2011-10-07 08:10:54.935,,,,,
37,0001717addec5a46218a1c54ca46302227eeb498,pcmcat180400050000,ColumbusDay_Fitness_20111009,2011-10-09 05:42:05.310,2011-10-09 05:41:30.663,,,,,
38,00018ef0bcccb5ad919cc89875c850b44fbd4c83,pcmcat180400050000,Nokia 5000,2011-08-12 13:20:30.628,2011-08-12 13:19:59.198,,,,,
39,0001b9a81bcc20fd6a3eb1dcb2387e9cf1fe918b,pcmcat225800050009,Sd card,2011-10-21 19:29:59.034,2011-10-21 19:29:29.161,,,,,
40,0001be1731ee7d1c519bc7e87110c9eb880cb396,abcat0715007,Hdmi,2011-08-31 20:19:33.008,2011-08-31 20:18:00.849,,,,,
41,0001be1731ee7d1c519bc7e87110c9eb880cb396,abcat0715002,xbox control,2011-10-19 18:37:54.515,2011-10-19 18:37:18.574,,,,,
42,0001cd0d10bbc585c9ba287c963e00873d4c0bfd,abcat0701001,gears of war,2011-10-09 17:22:14.322,2011-10-09 17:21:42.917,,,,,
43,0001cd0d10bbc585c9ba287c963e00873d4c0bfd,pcmcat243000050004,gears of war,2011-10-09 17:25:06.465,2011-10-09 17:21:42.917,,,,,
44,0001d27d074eb2f948cf766442488b487b802568,pcmcat209400050001,iPhone 4s,2011-10-07 08:27:12.246,2011-10-07 08:25:40.891,,,,,
45,0001e98ddd94562b37d51de1f2b68385749c6979,cat02015,one tree hill,2011-10-13 19:11:07.339,2011-10-13 19:08:09.000,,,,,
46,0001ef68a2eef2090913360ff9e0594fab474393,pcmcat167300050040,Surround system,2011-10-30 22:25:21.093,2011-10-30 22:22:58.868,,,,,
47,0001fb09f03fea4d04e2267ed3194c806839d997,abcat0515020,Razer blackwidow,2011-09-10 15:35:54.282,2011-09-10 15:35:47.249,,,,,
48,0002282bffcf4737a3900467fc5faf9346ac98c9,abcat0507009,power supplies,2011-10-26 00:29:36.895,2011-10-26 00:29:02.831,,,,,
49,000229467390b29404acd654e4648409f4dc420c,abcat0201011,iPod touch,2011-10-21 09:00:18.664,2011-10-21 08:59:44.840,,,,,